easy_admin:
  entities:
    Product:
      class: "App\\Entity\\Product"
      list:
        fields:
          - { property: 'imageName', type: 'image', base_path: '/images/products', label: 'image'}
          - name
          - description
          - updatedAt
      show: 
        fields:
          - { property: 'imageName', type: 'image', base_path: '/images/products', label: 'image'}
      form: 
        fields: 
          - { property: 'imageFile', type: 'vich_image', label: 'image' }
          - name
          - description
          - { property: 'Price', type: 'money', type_options: { divisor: 100 }}